// <auto-generated />
namespace Master_Approval_System.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addApprovalProcessTables : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addApprovalProcessTables));
        
        string IMigrationMetadata.Id
        {
            get { return "201811211718496_addApprovalProcessTables"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
